name: .NET

variables:
  - name: BuildParameters.RestoreBuildProjects
    value: '**/*.csproj'  
  - name: BuildParameters.TestProjects
    value: '**/*[Tt]ests/*.csproj'
 - name: BuildConfiguration
  value: Debug
     
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        projects: $(BuildParameters.RestoreBuildProjects)
        run: dotnet restore
      - displayName: Build
        inputs:
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration)
      #- name: Test
       # run: dotnet test --no-build --verbosity normal